export const CATEGORY = {
  ANY: 0,
  SOLID: 1,
  LIQUID: 2,
  GAS: 3,
  SAND: 4,
  ELECTRONICS: 5,
};
export const PARTICLE = {
  // --- UTILITY ---
  ANY: 0,

  // ---------------------------------------------------
  // --- SOLID PARTICLES -------------------------------
  // ---------------------------------------------------
  EMPTY: 1,
  STONE: 2,
  WALL: 3,
  WOOD: 4,
  METAL: 5,
  ICE: 6,
  GLASS: 7,

  // ---------------------------------------------------
  // --- LIQUID PARTICLES ------------------------------
  // ---------------------------------------------------
  WATER: 81,
  OIL: 82,
  LAVA: 83,
  MUD: 84,
  ACID: 85,
  STEAM: 86,
  ALCOHOL: 87,

  // ---------------------------------------------------
  // --- GAS PARTICLES ---------------------------------
  // ---------------------------------------------------
  SMOKE: 162,
  FIRE: 163,
  CHLORINE: 164,
  HYDROGEN: 165,
  VAPOR: 166,

  // ---------------------------------------------------
  // --- SAND PARTICLES --------------------------------
  // ---------------------------------------------------
  SAND: 241,
  WET_SAND: 242,
  DUST: 243,
  GRAVEL: 245,
  VOLCANIC_ASH: 247,
  COARSE_GRAVEL: 252,
  QUARTZ_SAND: 256,

  // ---------------------------------------------------
  // --- ELECTRONICS PARTICLES
  // ---------------------------------------------------
  TERMINAL: 321,
  SOURCE: 322,
  DRAIN: 323,
  BASE: 324,
  POWER: 345,
  OUTLET: 346,
  GROUND: 347,
  WIRE: 348,
  RESISTOR: 349,
};
export const CATEGORY_DATA = {
  [CATEGORY.SOLID]: {
    ID: CATEGORY.SOLID,
    NAME: "Solids",
    ICON: "./assets/icons/solid.svg",
  },
  [CATEGORY.LIQUID]: {
    ID: CATEGORY.LIQUID,
    NAME: "Liquids",
    ICON: "./assets/icons/liquid.svg",
  },
  [CATEGORY.GAS]: {
    ID: CATEGORY.GAS,
    NAME: "Gases",
    ICON: "./assets/icons/gas.svg",
  },
  [CATEGORY.SAND]: {
    ID: CATEGORY.SAND,
    NAME: "Sands",
    ICON: "./assets/icons/sand.svg",
  },
  [CATEGORY.ELECTRONICS]: {
    ID: CATEGORY.ELECTRONICS,
    NAME: "Electronics",
    ICON: "./assets/icons/electronics.svg",
  },
};
export const PARTICLE_DATA = {
  // --- SOLID Particles ---
  [PARTICLE.EMPTY]: {
    ID: PARTICLE.EMPTY,
    NAME: "Empty",
    COLOR: "#19191D", // or 2b2942
    CATEGORY: CATEGORY.SOLID,
    ISMOVABLE: false,
    DENSITY: 0,
  },
  [PARTICLE.STONE]: {
    ID: PARTICLE.STONE,
    NAME: "Stone",
    COLOR: "#706d69",
    CATEGORY: CATEGORY.SOLID,
    ISMOVABLE: false,
    DENSITY: 100,
  },
  [PARTICLE.WALL]: {
    ID: PARTICLE.WALL,
    NAME: "Wall",
    COLOR: "#888888",
    CATEGORY: CATEGORY.SOLID,
    ISMOVABLE: false,
    DENSITY: 9999,
  },
  [PARTICLE.WOOD]: {
    ID: PARTICLE.WOOD,
    NAME: "Wood",
    COLOR: "#8B4513",
    CATEGORY: CATEGORY.SOLID,
    ISMOVABLE: false,
    DENSITY: 50,
  },
  [PARTICLE.METAL]: {
    ID: PARTICLE.METAL,
    NAME: "Metal",
    COLOR: "#A9A9A9",
    CATEGORY: CATEGORY.SOLID,
    ISMOVABLE: false,
    DENSITY: 200,
  },
  [PARTICLE.ICE]: {
    ID: PARTICLE.ICE,
    NAME: "Ice",
    COLOR: "#4295b0",
    CATEGORY: CATEGORY.SOLID,
    ISMOVABLE: false,
    DENSITY: 90,
  },
  [PARTICLE.GLASS]: {
    ID: PARTICLE.GLASS,
    NAME: "Glass",
    COLOR: "#bde3e8",
    CATEGORY: CATEGORY.SOLID,
    ISMOVABLE: false,
    DENSITY: 150,
  },
  // --- LIQUID Particles ---
  [PARTICLE.WATER]: {
    ID: PARTICLE.WATER,
    NAME: "Water",
    COLOR: "#0088cc",
    CATEGORY: CATEGORY.LIQUID,
    ISMOVABLE: true,
    DENSITY: 1,
    MAXCONCENTRATION: 10,
  },
  [PARTICLE.OIL]: {
    ID: PARTICLE.OIL,
    NAME: "Oil",
    COLOR: "#282828",
    CATEGORY: CATEGORY.LIQUID,
    ISMOVABLE: true,
    DENSITY: 0.8,
    MAXCONCENTRATION: 15,
  },
  [PARTICLE.LAVA]: {
    ID: PARTICLE.LAVA,
    NAME: "Lava",
    COLOR: "#d7430c",
    CATEGORY: CATEGORY.LIQUID,
    ISMOVABLE: true,
    DENSITY: 3.5,
    MAXCONCENTRATION: 5,
  },
  [PARTICLE.MUD]: {
    ID: PARTICLE.MUD,
    NAME: "Mud",
    COLOR: "#6B4423",
    CATEGORY: CATEGORY.LIQUID,
    ISMOVABLE: true,
    DENSITY: 1.5,
    MAXCONCENTRATION: 8,
  },
  [PARTICLE.ACID]: {
    // Liquid 5
    ID: PARTICLE.ACID,
    NAME: "Acid",
    COLOR: "#2fcc2f",
    CATEGORY: CATEGORY.LIQUID,
    ISMOVABLE: true,
    DENSITY: 1.1,
    MAXCONCENTRATION: 12,
  },
  [PARTICLE.STEAM]: {
    ID: PARTICLE.STEAM,
    NAME: "Steam",
    COLOR: "#c7c7c7",
    CATEGORY: CATEGORY.LIQUID,
    ISMOVABLE: true,
    DENSITY: 0.5,
    MAXCONCENTRATION: 20,
  },
  [PARTICLE.ALCOHOL]: {
    ID: PARTICLE.ALCOHOL,
    NAME: "Alcohol",
    COLOR: "#FFFFFF",
    CATEGORY: CATEGORY.LIQUID,
    ISMOVABLE: true,
    DENSITY: 0.78,
    MAXCONCENTRATION: 10,
  },
  // --- GAS PARTICLES ---
  [PARTICLE.SMOKE]: {
    ID: PARTICLE.SMOKE,
    NAME: "Smoke",
    COLOR: "#444444",
    CATEGORY: CATEGORY.GAS,
    ISMOVABLE: true,
    DENSITY: 0.1,
  },
  [PARTICLE.FIRE]: {
    ID: PARTICLE.FIRE,
    NAME: "Fire",
    COLOR: "#f7c040", // Whatever dude, nothing works for this stupid gas
    CATEGORY: CATEGORY.GAS,
    ISMOVABLE: true,
    DENSITY: -0.1,
  },
  [PARTICLE.CHLORINE]: {
    ID: PARTICLE.CHLORINE,
    NAME: "Chlorine",
    COLOR: "#c1c10e",
    CATEGORY: CATEGORY.GAS,
    ISMOVABLE: true,
    DENSITY: 2.0,
  },
  [PARTICLE.HYDROGEN]: {
    ID: PARTICLE.HYDROGEN,
    NAME: "Hydrogen",
    COLOR: "#ADD8E6",
    CATEGORY: CATEGORY.GAS,
    ISMOVABLE: true,
    DENSITY: -0.5,
  },
  [PARTICLE.VAPOR]: {
    ID: PARTICLE.VAPOR,
    NAME: "Vapor",
    COLOR: "#A9A9A9",
    CATEGORY: CATEGORY.GAS,
    ISMOVABLE: true,
    DENSITY: 0.05,
  },
  // --- SAND Particles ---
  [PARTICLE.SAND]: {
    ID: PARTICLE.SAND,
    NAME: "Sand",
    COLOR: "#cbc439",
    CATEGORY: CATEGORY.SAND,
    ISMOVABLE: true,
    DENSITY: 2,
    REPOSE_ANGLE: 45,
  },
  [PARTICLE.WET_SAND]: {
    ID: PARTICLE.WET_SAND,
    NAME: "Wet Sand",
    COLOR: "#9c8d5d",
    CATEGORY: CATEGORY.SAND,
    ISMOVABLE: true,
    DENSITY: 3,
    REPOSE_ANGLE: 55,
  },
  [PARTICLE.DUST]: {
    ID: PARTICLE.DUST,
    NAME: "Dust",
    COLOR: "#b6b5a3",
    CATEGORY: CATEGORY.SAND,
    ISMOVABLE: true,
    DENSITY: 1,
    REPOSE_ANGLE: 20,
  },
  [PARTICLE.GRAVEL]: {
    ID: PARTICLE.GRAVEL,
    NAME: "Gravel",
    COLOR: "#4a443c",
    CATEGORY: CATEGORY.SAND,
    ISMOVABLE: true,
    DENSITY: 4,
    REPOSE_ANGLE: 30,
  },
  [PARTICLE.VOLCANIC_ASH]: {
    ID: PARTICLE.VOLCANIC_ASH,
    NAME: "Volcanic Ash",
    COLOR: "#3b3b3b",
    CATEGORY: CATEGORY.SAND,
    ISMOVABLE: true,
    DENSITY: 1.5,
    REPOSE_ANGLE: 15,
  },
  [PARTICLE.COARSE_GRAVEL]: {
    ID: PARTICLE.COARSE_GRAVEL,
    NAME: "Coarse Gravel",
    COLOR: "#6b645b",
    CATEGORY: CATEGORY.SAND,
    ISMOVABLE: true,
    DENSITY: 2.7,
    REPOSE_ANGLE: 50,
  },
  [PARTICLE.QUARTZ_SAND]: {
    ID: PARTICLE.QUARTZ_SAND,
    NAME: "Quartz Sand",
    COLOR: "#c7c7c3",
    CATEGORY: CATEGORY.SAND,
    ISMOVABLE: true,
    DENSITY: 2.3,
    REPOSE_ANGLE: 70,
  },
  // --- ELECTRONICS Particles ---
  [PARTICLE.TERMINAL]: {
    ID: PARTICLE.TERMINAL,
    NAME: "Terminal",
    COLOR: "#046962",
    CATEGORY: CATEGORY.ELECTRONICS,
    ISMOVABLE: false,
    DENSITY: 0,
  },
  [PARTICLE.SOURCE]: {
    ID: PARTICLE.SOURCE,
    NAME: "Source",
    COLOR: "#228199",
    CATEGORY: CATEGORY.ELECTRONICS,
    ISMOVABLE: false,
    DENSITY: 0,
  },
  [PARTICLE.DRAIN]: {
    ID: PARTICLE.DRAIN,
    NAME: "Drain",
    COLOR: "#8c470e",
    CATEGORY: CATEGORY.ELECTRONICS,
    ISMOVABLE: false,
    DENSITY: 0,
  },
  [PARTICLE.BASE]: {
    ID: PARTICLE.BASE,
    NAME: "Base",
    COLOR: "#046962",
    CATEGORY: CATEGORY.ELECTRONICS,
    ISMOVABLE: false,
    DENSITY: 0,
  },
  [PARTICLE.POWER]: {
    ID: PARTICLE.POWER,
    NAME: "Power",
    COLOR: "#ac3232",
    CATEGORY: CATEGORY.ELECTRONICS,
    ISMOVABLE: false,
    DENSITY: 0,
  },
  [PARTICLE.OUTLET]: {
    ID: PARTICLE.OUTLET,
    NAME: "Outlet",
    COLOR: "#ac3232",
    CATEGORY: CATEGORY.ELECTRONICS,
    ISMOVABLE: false,
    DENSITY: 0,
  },
  [PARTICLE.GROUND]: {
    ID: PARTICLE.GROUND,
    NAME: "Ground",
    COLOR: "#847e87",
    CATEGORY: CATEGORY.ELECTRONICS,
    ISMOVABLE: false,
    DENSITY: 0,
  },
  [PARTICLE.WIRE]: {
    ID: PARTICLE.WIRE,
    NAME: "Wire",
    COLOR: "#3f3f74",
    CATEGORY: CATEGORY.ELECTRONICS,
    ISMOVABLE: false,
    DENSITY: 0,
  },
  [PARTICLE.RESISTOR]: {
    ID: PARTICLE.RESISTOR,
    NAME: "Resistor",
    COLOR: "#fbf236",
    CATEGORY: CATEGORY.ELECTRONICS,
    ISMOVABLE: false,
    DENSITY: 0,
  },
};
